[package]
name = "granit"
version.workspace = true
license.workspace = true
description = "Minimal desktop note-taking app with an integrated AI agent"
authors = ["LHelge"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "granit_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2.0.20"
serde_yml = "0.0.13"
tauri-plugin-dialog = "2.7.2"
granit-types = { path = "../granit-types" }
pulldown-cmark = "0.13.4"
chrono = { version = "0.4.45", features = ["serde"] }
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros"] }
rig-core = "0.42.0"
futures = "0.3.34"
font-kit = "0.14.3"
reqwest = { version = "0.13.4", features = ["json", "query"] }
html-to-markdown-rs = "3.11.4"
tauri-plugin-store = "2.4.4"
tauri-plugin-updater = "2"
tera = "2.2.0"
log = "0.4"
fastembed = "6"
rkyv = { version = "0.8", features = ["alloc"] }
tauri-plugin-log = "2"
atomic-write-file = { version = "0.3", features = ["unnamed-tmpfile"] }
parking_lot = "0.12"
rig-agent = "0.42.0"

[dev-dependencies]
tempfile = "3.27.0"
